site_name: Solital Framework v1.x
repo_url: https://github.com/solital/docs-v1/tree/gh-pages
pages:
  - Welcome: index.md
  - Starting: starting.md
  - Installation: installation.md
  - Vinci Console: vinci.md
  - Components: components.md
  - Routes: routes.md
  - Sessions and Cookies: sessions_cookies.md
  - Input & params : input.params.md
  - JSON: json.md
  - Validation: validation.md
  - Events: events.md
  - Authenticate: auth.md
  - Dependency Container (PSR-11): injection.md
  - Cache (PSR-16): cache.md
  - Logger (PSR-3): logger.md
  - Security: security.md
  - Handling Folders and Files: folders-files.md
  - HTTP Client: http.md
  - HTTP Cache: http-cache.md
  - Katrina ORM: katrina.md
  - Deploy: deploy.md
theme: readthedocs