site_name: Solital Framework v1.0
repo_url: https://github.com/solital/docs-v1/tree/gh-pages
pages:
  - Welcome: index.md
  - Starting: starting.md
  - Installation: installation.md
  - Vinci Console: vinci.md
  - Components: components.md
  - Routes: routes.md
  - Requisitions: requisitions.md
  - Input & params : input.params.md
  - Events: events.md
  - Authenticate: auth.md
  - Dependency Container: injection.md
  - Cache: cache.md
  - Security: security.md
  - Handling Folders and Files: folders-files.md
  - HTTP Client: http.md
  - Katrina ORM: katrina.md
theme: readthedocs